version: '3.3'
services:
  test:
    image: pyspark-fun-test
    build:
      context: .
      dockerfile: Dockerfile-test
  run:
    image: pyspark-fun-run
    build:
      context: .
      dockerfile: Dockerfile-run
    ports:
      - '80:8888'